searchTerms = [
                    'fundamental analysis',
                    'Stock Valuation Models',
                    'Free Cash Flows',
                    'how to pick stocks to buy',
                    'how to research stocks',
                    'Discounted Cash Flow Model',
                    'How do I pick the best stocks',
                    'Options trading for beginners',
                    'how to invest in stocks',
                    'value stocks',
                    'Managing your own stock portfolio',
                    'New ai apps',
                    'Top ten ai apps',
                    'mobile app review',
                    'investing for beginners',
                    'How do I pick the best stocks: investing for beginners',
                    'stock market for beginners',
                    'how to pick stocks',
                    'how to invest in the stock market',
                    'how to pick stocks to invest in',
                    'stock investing for beginners',
                    'technical analysis',
                ]
SCOPES = ['https://www.googleapis.com/auth/youtube','https://www.googleapis.com/auth/youtube.readonly']